package com.proyectosdesarrollo.patronesdiseno.factory;

public interface Enemy {
    /**
     * TODAS LAS CLASES QUE IMPLEMENTEN ENEMY TENDRAN IMPLEMENTAR EL METODO ATACAR, 
     * ESTO ES COMO UN CONTRATO, HABRA 2 TIPOS DE ENEMIGOS, WARRIOR Y MAGO
     * LAS INTERFACES MUCHAS VECES SE UTLIZAN PARA LA HERENCIA MULTIPLE, EN JAVA
     * NO EXISTE HERENCIA MULTIPLE, PERO UNA CLASE SI PUEDE IMPLEMENTAR A MUCHAS 
     */
    
    void attack();
}
